[package]
name = "nlu-utils-py"
version = "0.6.0-SNAPSHOT"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]

[lib]
name = "nlu_utils_py"
crate-type = ["cdylib"]

[dependencies]
nlu-utils = { path = "../.."}
cpython = { version="0.1", default-features=false }
